# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5bfd0d79db27e8069ce84de984d8d3b1397d0074e65429bfa77ffdcb81ab4ec6d2cf90d8c72c5b62697425d47df227cedb1ea90f6a4480c81c69cf47accf4b6

test:
  secret_key_base: d09127e902cbcad4d0ae5d959da0f981e32121ed7659625bea65795ecc1fb2e1e62076e09aeac6970978d258c8d29306813635e884bb958918b7f0b5f9d2eb26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
